# database settings
server:
  port: 10000

spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/recommendsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      use-global-data-source-stat: true
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # jpa
  jpa:
    properties:
      hibernate:
        formate_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  # security
  security:
    user:
      name: admin
      password: admin
  # redis settings
  redis:
    host: localhost
    database: 0 # redis 数据库索引(默认为0
    port: 6379
    password:
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
  devtools:
    restart:
      enabled: true
# jwt
jwt:
  tokenHeader: Authorization # JWT 请求头
  secret: recommendSystem # 加密密钥
  expiration: 604800 #　过期时间：60*60*24( 1 day　)
  tokenHead: Bearer
# elasticsearch
elasticsearch:
  hostAndPort: 47.94.38.213:9200

# swagger2
swagger2:
  version: 1.0
  enable: true
  scanBasePackage: com.utopia.demo.controller

# redis -> key:value


